CREATE PROCEDURE Activar_Producto
	@Id_Producto UNIQUEIDENTIFIER
AS
BEGIN
	SET NOCOUNT ON;

	BEGIN TRANSACTION

		UPDATE dbo.Producto_TB
		SET Id_Estado = 1
		WHERE Id_Producto = @Id_Producto

	COMMIT TRANSACTION
END
