
CREATE OR ALTER PROCEDURE Agregar_Proveedor
	@Id_Proveedor UNIQUEIDENTIFIER,
	@Nombre_Proveedor VARCHAR(MAX),
	@Telefono_Proveedor VARCHAR(MAX),
	@Correo_Proveedor VARCHAR(MAX)
	
AS
BEGIN
	SET NOCOUNT ON;

	BEGIN TRANSACTION

		INSERT INTO [dbo].[PROVEEDOR_TB]
		(
			[NOMBRE_PROVEEDOR],
			[ID_DIRECCION],
			[ID_ESTADO]
		)
		VALUES
		(
			@Nombre_Proveedor,
			NULL,
			1
		)

		DECLARE @IdInt INT = CAST(SCOPE_IDENTITY() AS INT)
		DECLARE @IdGuid UNIQUEIDENTIFIER = CONVERT(UNIQUEIDENTIFIER, '00000000-0000-0000-0000-' + RIGHT('000000000000' + CONVERT(VARCHAR(8), CONVERT(VARBINARY(4), @IdInt), 2), 12))

		INSERT INTO [dbo].[PROVEEDOR_TELEFONO_TB] ([ID_PROVEEDOR], [TELEFONO])
		VALUES (@IdInt, ISNULL(@Telefono_Proveedor, ''))

		INSERT INTO [dbo].[PROVEEDOR_CORREO_TB] ([ID_PROVEEDOR], [CORREO])
		VALUES (@IdInt, ISNULL(@Correo_Proveedor, ''))

		SELECT @IdGuid

	COMMIT TRANSACTION
END