
CREATE OR ALTER PROCEDURE Agregar_Producto 
	@Id_Producto UNIQUEIDENTIFIER,
	@Nombre_Producto VARCHAR(MAX),
	@Precio_Venta DECIMAL(18,0),
	@Stock_Actual INT
AS
BEGIN
	SET NOCOUNT ON;

	BEGIN TRANSACTION

		INSERT INTO [dbo].[PRODUCTO_TB]
		(
			[NOMBRE_PRODUCTO],
			[PRECIO_VENTA],
			[STOCK_ACTUAL],
			[ID_ESTADO]
		)
		VALUES
		(
			@Nombre_Producto,
			@Precio_Venta,
			@Stock_Actual,
			1
		)

		DECLARE @IdInt INT = CAST(SCOPE_IDENTITY() AS INT)
		DECLARE @IdGuid UNIQUEIDENTIFIER = CONVERT(UNIQUEIDENTIFIER, '00000000-0000-0000-0000-' + RIGHT('000000000000' + CONVERT(VARCHAR(8), CONVERT(VARBINARY(4), @IdInt), 2), 12))

		SELECT @IdGuid

	COMMIT TRANSACTION
END