
CREATE OR ALTER PROCEDURE Eliminar_Proveedor
	@Id_Proveedor UNIQUEIDENTIFIER
AS
BEGIN
	SET NOCOUNT ON;
	DECLARE @IdInt INT = CONVERT(INT, CONVERT(VARBINARY(4), RIGHT(CONVERT(VARCHAR(36), @Id_Proveedor), 8), 2));

	BEGIN TRANSACTION

		UPDATE dbo.PROVEEDOR_TB
		SET ID_ESTADO = 2
		WHERE ID_PROVEEDOR = @IdInt

		SELECT @Id_Proveedor

	COMMIT TRANSACTION
END