
CREATE PROCEDURE Eliminar_Proveedor
	@Id_Proveedor UNIQUEIDENTIFIER
AS
BEGIN
	SET NOCOUNT ON;

	BEGIN TRANSACTION

		UPDATE dbo.Proveedor_TB
		SET Estado = 2
		WHERE Id_Proveedor = @Id_Proveedor

	COMMIT TRANSACTION
END