
CREATE OR ALTER PROCEDURE Eliminar_Producto
	@Id_Producto UNIQUEIDENTIFIER
AS
BEGIN
	SET NOCOUNT ON;
	DECLARE @IdInt INT = CONVERT(INT, CONVERT(VARBINARY(4), RIGHT(CONVERT(VARCHAR(36), @Id_Producto), 8), 2));

	BEGIN TRANSACTION

		UPDATE dbo.PRODUCTO_TB
		SET ID_ESTADO = 2
		WHERE ID_PRODUCTO = @IdInt

		SELECT @Id_Producto

	COMMIT TRANSACTION
END