
CREATE OR ALTER PROCEDURE Obtener_Proveedores
AS
BEGIN
	SET NOCOUNT ON;

	SELECT
		CONVERT(UNIQUEIDENTIFIER, '00000000-0000-0000-0000-' + RIGHT('000000000000' + CONVERT(VARCHAR(8), CONVERT(VARBINARY(4), p.ID_PROVEEDOR), 2), 12)) AS Id_Proveedor,
		p.ID_ESTADO AS Estado,
		p.NOMBRE_PROVEEDOR AS Nombre_Proveedor,
		pt.TELEFONO AS Telefono_Proveedor,
		pc.CORREO AS Correo_Proveedor
	FROM dbo.PROVEEDOR_TB p
	OUTER APPLY (
		SELECT TOP 1 TELEFONO
		FROM dbo.PROVEEDOR_TELEFONO_TB
		WHERE ID_PROVEEDOR = p.ID_PROVEEDOR
		ORDER BY ID_PROVEEDOR_TELEFONO DESC
	) pt
	OUTER APPLY (
		SELECT TOP 1 CORREO
		FROM dbo.PROVEEDOR_CORREO_TB
		WHERE ID_PROVEEDOR = p.ID_PROVEEDOR
		ORDER BY ID_PROVEEDOR_CORREO DESC
	) pc
	WHERE p.ID_ESTADO = 1
END