
CREATE PROCEDURE Eliminar_Producto
	@Id_Producto UNIQUEIDENTIFIER
AS
BEGIN
	SET NOCOUNT ON;

	BEGIN TRANSACTION

		UPDATE dbo.Producto_TB
		SET Estado = 2
		WHERE Id_Producto = @Id_Producto

	COMMIT TRANSACTION
END